spring:
  application:
    name: order-service

  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/changelog.yaml

  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    spring: INFO
    io.github.resilience4j.circuitbreaker: DEBUG
  file:
    name: logs/log.log

resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

userClient:
  url: http://localhost:8082